<?php
  $lang['campo1']		= 'Cotacao / Pedido';
  $lang['campo2'] 		= 'Data de abertura';
  $lang['campo3']		= 'Data de aprovacao';
  $lang['campo4']		= 'Prazo de entrega';
  $lang['origem'] 		= 'Loja';
  $lang['destino'] 		= 'Fornecedor';
  $lang['descricao'] 	= 'Produto';
  $lang['descricao2'] 	= 'Cod. Barras';
  $lang['quant'] 		= 'Quant';
  $lang['preco'] 		= 'Valor';
  $lang['desconto'] 	= 'Desconto';
  $lang['total'] 		= 'TOTAL';
  $lang['page'] 		= 'Pagina';
  $lang['page_of'] 		= 'de';
  $lang['from'] 		= 'de';
  $lang['to'] 		= 'para';
  $lang['date'] 		= 'data';
  $lang['time'] 		= 'hora';
  $lang['product'] 		= 'DECRIÇÃO';
  $lang['qty'] 		= 'QTDE';
  $lang['number'] 		= 'Numero';
  $lang['due'] 			= 'Data de vencimento';
  $lang['price'] 		= 'Valor';
  $lang['discount'] 	= 'Desconto';
  $lang['vat'] 			= 'Unit';
?>