pipelines:
  branches:
    develop:
      - step:
          name: ssh-develop
          script:
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SSH_SERVER
                MODE: 'command'
                COMMAND: 'cd public_html/desenvolvimento; git pull origin develop; composer install; composer run migration migrate'
                PORT: $SSH_PORT
    release/*:
      - step:
          name: ssh-release
          script:
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SSH_SERVER
                MODE: 'command'
                COMMAND: 'cd public_html/homologacao; git fetch; git checkout release/${BITBUCKET_BRANCH##release/}; composer update; composer run migration migrate'
                PORT: $SSH_PORT