<?php
  $lang['number']		= 'Numero';
  $lang['date'] 		= 'Data de emissao';
  $lang['time']			= 'Forma de pagamento';
  $lang['due'] 			= 'Data de vencimento';
  $lang['to'] 			= 'Cobrar de';
  $lang['from'] 		= 'Empresa';
  $lang['product'] 		= 'Descricao';
  $lang['qty'] 			= 'Quant';
  $lang['price'] 		= 'Valor';
  $lang['discount'] 	= 'Desconto';
  $lang['vat'] 			= 'Unit';
  $lang['total'] 		= 'Total';
  $lang['page'] 		= 'Pagina';
  $lang['page_of'] 		= 'de';
?>